services:
  cups:
    build:
      context: .
      args:
        - ADMINUSER=print
        - ADMINPASS=printpass
        - PRINTER_NAME=ip7200
        - PRINTER_DESCRIPTION=Canon Pixma ip7200
        - PRINTER_LOCATION=Buero
    ports:
      - "631:631"   # IPP/IPPS and webserver
      - "5353:5353" # mDNS
      - "139:139"   # SMB port      
    volumes:
      -  /dev/usb/lp0:/dev/usb/lp0 # route USB dev 
      
