services:
  cups:
    build:
      context: .
      args:
        - USERNAME=print
        - PASSWORD=printpass
    ports:
      - "631:631"   # IPP/IPPS and webserver
      - "5353:5353" # mDNS
      - "139:139"   # SMB port      
